# Generated by Django 6.0.1 on 2026-02-04 00:40

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name ='RetailData',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('merchant', models.TextField()),
                ('sku', models.TextField()),
                ('country', models.CharField(max_length = 3)),
                ('retailer', models.TextField(blank = True, null = True)),
                ('segment', models.CharField(
                    blank = True, 
                    choices = [('first_party', 'First Party'), ('third_party', 'Third Party')], 
                    max_length = 20, 
                    null = True
                )),
            ],
            options = {
                'unique_together': {('merchant', 'sku', 'country')},
            },
        ),
    ]
